DROP TABLE IF EXISTS played;
DROP TABLE IF EXISTS playerItem;
DROP TABLE IF EXISTS gameGenre;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS genre;